name: RieMoniqueCherie
favicon: null
layout_spectrum: 0.2210203679278493
typography_spectrum: 0.516887393547222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfdf8'
    - '#dec3b0'
    - '#516674'
    - '#d19887'
    - '#7aa7e0'
  brandStrength: 0.9407961589749902
  lightness: 0.30756596964783967
  saturation: 0.2358913840726018
  rhythmicContrast: 0.42369501222856343
purpose: []
